project_id = "jdnqaxldwyembanatnqd"

[functions.ai-chat]
verify_jwt = false

[functions.telegram-notify]
verify_jwt = false

[functions.telegram-bot-webhook]
verify_jwt = false

[functions.telegram-scheduler]
verify_jwt = false

[functions.telegram-manage]
verify_jwt = false
